### ISSUE TITLE
No funcina!!!

### ISSUE THREAD

**Issue by jcalles** [JuananOc/tutorial-kubernetes-ubuntu#1]
fatal: [prueba] => error while evaluating conditional: 'Text file busy' not in result.stdout and 'true' in result.failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jcalles/infraestructure.retry

prueba                     : ok=16   changed=6    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by JuananOc** [comment]
Buenas, he actualizado el repositorio. Asegúrate de que tienes la última versión, destruye la máquina virtual antigua con el comando `vagrant destroy` y vuelve a crearla otra vez con `vagrant up`.

¡Gracias por el aviso!

Doy por cerrado el issue, si tienes algún problema no dudes en volver a comentarlo 💃
